[package]
categories = ["embedded", "no-std"]
description = "I2C/SPI driver for the SSD1306 OLED display controller"
name = "ssd1306"
version = "0.1.0"
authors = ["James Waples <jamwaffles@gmail.com>"]
keywords = ["no-std", "ssd1306", "oled", "embedded", "embedded-hal-driver"]
repository = "https://github.com/jamwaffles/ssd1306"
documentation = "https://jamwaffles.github.io/ssd1306"
readme = "README.md"
license = "MIT OR Apache-2.0"
exclude = [
	".travis.yml",
	".gitignore"
]

[badges]
travis-ci = { repository = "jamwaffles/ssd1306", branch = "master" }

[dependencies]
embedded-hal = "0.1.2"

[dependencies.embedded-graphics]
version = "0.1.1"
optional = true

[dev-dependencies]
cortex-m = "0.4.3"
aligned = "0.1.1"
cortex-m-rtfm = "0.3.2"
cortex-m-rtfm-macros = "0.3.1"
cortex-m-rt = "0.4.0"
panic-abort = "0.1.0"

# Must be installed from Git currently, not sure why it's not on crates.io
# TODO: Replace this with a "normal" dependency in the future
# TODO: Replace with @japaric's HAL once I2C support has landed
[dev-dependencies.stm32f103xx-hal]
git = "https://github.com/ilya-epifanov/stm32f103xx-hal.git"
branch = "i2c-support"
features = ["rt"]
version = "*"

# disable both incremental compilation and parallel codegen to reduce the chances of running into
# rust-lang/rust#47074
[profile.dev]
codegen-units = 1
incremental = false

[profile.release]
debug = true
lto = true

[features]
default = ["graphics"]
graphics = ["embedded-graphics"]
