[package]
categories = ["embedded", "no-std"]
description = "I2C/SPI driver for the SSD1306 OLED display controller"
name = "ssd1306"
version = "0.1.0"
authors = ["James Waples <jamwaffles@gmail.com>"]
keywords = ["no-std", "ssd1306", "oled", "embedded", "embedded-hal-driver"]
repository = "https://github.com/jamwaffles/ssd1306"
documentation = "https://jamwaffles.github.io/ssd1306"
readme = "README.md"
license = "MIT OR Apache-2.0"
exclude = [
	".travis.yml",
	".gitignore"
]

[badges]
travis-ci = { repository = "jamwaffles/ssd1306", branch = "master" }

[dependencies]
embedded-hal = "0.2.1"

[dependencies.embedded-graphics]
version = "0.3.0"
optional = true

[dev-dependencies]
cortex-m = "0.5.6"
aligned = "0.2.0"
cortex-m-rtfm = "0.3.4"
cortex-m-rtfm-macros = "0.3.2"
cortex-m-rt = "0.5.2"
panic-abort = "0.2.0"

# Must be installed from Git currently, not sure why it's not on crates.io
# TODO: Replace this with a "normal" dependency in the future
# TODO: Replace with @japaric's HAL once I2C support has landed
[dependencies.stm32f103xx-hal]
git = "https://github.com/ilya-epifanov/stm32f103xx-hal.git"
rev = "3a8d64d3605b5eac9fd15eea0ba25319fbb8375c"
features = ["rt"]
version = "*"

[profile.dev]
incremental = false
codegen-units = 1

[profile.release]
codegen-units = 1
debug = true
lto = true

[features]
default = ["graphics"]
graphics = ["embedded-graphics"]
